name: Latest blog post workflow
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    permissions:
      contents: write # To write the generated contents to the readme
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in medium.com posts
        uses: SaiCharan1394/SaiCharan1394/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@akkirajusaicharan" # Replace 'username' with the actual dev.to username that you want to fetch the blog posts from

